version: '3.8'
services:
  mcp-jina-ai:
    image: joebuildsstuff/mcp-jina-ai:latest
    container_name: mcp-jina-ai
    ports:
      - "8081:8080"
    environment:
      - JINA_API_KEY=${JINA_API_KEY}
    restart: unless-stopped
