version: "3.7"

volumes:
  searxng-data:
  searxng-cache:

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8087:8087"
    volumes:
      - searxng-data:/etc/searxng
      - searxng-cache:/var/cache/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
    restart: unless-stopped
